channels:
  - PyPi
  - conda-forge
  - pytorch 
  - nvidia
dependencies:
  - absl-py
  - arxiv
  - bert_score
  - black
  - chroma-hnswlib
  - chromadb
  - docformatter
  - evaluate
  - flake8
  - ipykernel
  - ipython
  - ipywidgets
  - llama-index-embeddings-openai
  - llama-index-llms-openai
  - mypy
  - nltk
  - openai
  - pip
  - pre-commit
  - pydantic
  - pydocstyle[version='>=6.1.1']
  - pytest
  - python-dotenv
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - rouge-score
  - scikit-learn
  - scipy
  - seaborn
  - sentence-transformers
  - tiktoken=0.7
  - pip:
    - git+https://github.com/alvinwan/TexSoup@master
    - llama-index-vector-stores-chroma
    - pdf2docx
